---

- include_tasks: install.yml
- include_tasks: configure-logging.yml
- include_tasks: configure-domain.yml
- include_tasks: initial-entries.yml
- include_tasks: service-accounts.yml
  when: do_service_accounts|bool
