---

- name: Set Service OU DN in fact
  set_fact:
    service_ou_dn: "ou={{ service_ou }},{{ domain_dn }}"

- name: Add OU for LDAP service accounts
  ldap_entry:
    dn: "{{ service_ou_dn }}"
    bind_dn: "cn={{ admin_dn | default('manager') }}, {{ domain_dn }}"
    bind_pw: "{{ admin_password }}"
    state: present
    objectClass:
      - top
      - organizationalUnit
    attributes:
      ou: "{{ service_ou }}"

- name: Create service users
  ldap_entry:
    dn: "cn={{ item.key }},{{ service_ou_dn }}"
    bind_dn: "cn={{ admin_dn | default('manager') }}, {{ domain_dn }}"
    bind_pw: "{{ admin_password }}"
    state: present
    objectClass:
      - organizationalRole
      - simpleSecurityObject
    attributes:
      cn: "{{ item.key }}"
      userPassword: "{{ item.value }}"
  with_dict: "{{ ldap_service_accounts }}"
  when: ldap_service_accounts is defined
  no_log: true
